source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AGSwiftNotif_Example', :exclusive => true do
  pod 'AGSwiftNotif', :path => '../'
end

target 'AGSwiftNotif_Tests', :exclusive => true do
  pod 'AGSwiftNotif', :path => '../'

  
end
